-- 권장: Flyway/Liquibase 같은 마이그레이션 파일로 1회 적용
-- 예: V1__init.sql

-- updated_at 자동 갱신용 함수
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- 사용자 테이블 (기존 user 대체)
CREATE TABLE app_user (
  user_id        varchar(100) PRIMARY KEY,
  nickname       varchar(100) NOT NULL,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  last_login_at  timestamptz
);

-- 작업 테이블
CREATE TABLE work (
  work_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_name   varchar(200) NOT NULL,
  user_id     varchar(100) NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fk_work_user
    FOREIGN KEY (user_id)
    REFERENCES app_user (user_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE INDEX idx_work_user_id ON work (user_id);

-- 작업 상세 테이블
CREATE TABLE work_detail (
  work_detail_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_set_id          integer NOT NULL,
  work_detail_name     varchar(200) NOT NULL,
  work_detail_count    varchar(100),
  work_id              bigint NOT NULL,
  work_detail_category varchar(100),
  memo                 text,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fk_work_detail_work
    FOREIGN KEY (work_id)
    REFERENCES work (work_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE INDEX idx_work_detail_work_id ON work_detail (work_id);

-- updated_at 트리거 적용
CREATE TRIGGER trg_app_user_updated_at
BEFORE UPDATE ON app_user
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_work_updated_at
BEFORE UPDATE ON work
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_work_detail_updated_at
BEFORE UPDATE ON work_detail
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
