-- 권장: Flyway/Liquibase 같은 마이그레이션 파일로 1회 적용
-- 예: V1__init.sql

CREATE TABLE IF NOT EXISTS "user" (
  "USER_ID"     varchar(100) PRIMARY KEY,
  "NICKNAME"    varchar(100) NOT NULL,
  "CREATE_DATE" date NOT NULL DEFAULT current_date,
  "EDIT_DATE"   timestamp DEFAULT now(),
  "LOGIN_DATE"  timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "work" (
  "WORK_ID"     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "WORK_NAME"   varchar(200) NOT NULL,
  "USER_ID"     varchar(100) NOT NULL,
  "CREATE_DATE" timestamp NOT NULL DEFAULT now(),
  "EDIT_DATE"   timestamp DEFAULT now(),
  CONSTRAINT "work_ibfk_1"
    FOREIGN KEY ("USER_ID")
    REFERENCES "user" ("USER_ID")
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "work_detail" (
  "WORK_DETAIL_ID"       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "WORK_SET_ID"          integer NOT NULL,
  "WORK_DETAIL_NAME"     varchar(200) NOT NULL,
  "WORK_DETAIL_COUNT"    varchar(100),
  "WORK_ID"              integer NOT NULL,
  "CREATE_DATE"          timestamp NOT NULL DEFAULT now(),
  "EDIT_DATE"            timestamp DEFAULT now(),
  "WORK_DETAIL_CATEGORY" varchar(100),
  "MEMO"                 text,
  CONSTRAINT "work_detail_ibfk_1"
    FOREIGN KEY ("WORK_ID")
    REFERENCES "work" ("WORK_ID")
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
